# This workflow installs dependencies, runs tests, and lints the codebase
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Cache NLTK data
      uses: actions/cache@v4
      with:
        path: ~/nltk_data
        key: ${{ runner.os }}-nltk-3.13-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-nltk-3.13-
          ${{ runner.os }}-nltk-
    - name: Cache sentence-transformers model
      uses: actions/cache@v4
      with:
        path: ~/.cache/torch/sentence_transformers
        key: ${{ runner.os }}-st-3.13-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-st-3.13-
          ${{ runner.os }}-st-
    - name: Install dependencies
      run: make install
    - name: Download sentence-transformer model
      run: python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('sentence-transformers/paraphrase-MiniLM-L3-v2')"
    - name: Lint with flake8
      run: make lint
    - name: Test with pytest
      run: make test
